import em from 'utils/em';

const DEFAULT_BORDER_WIDTH = 0.5;
const DEFAULT_LIST_ITEM_FONT_SIZE = em(1.2);
const DEFAULT_LIST_ITEM_HEIGHT = 70;
const COLLAPSIBLE_MENU_HEIGHT = 50;
const COLLAPSIBLE_ICON_SIZE = em(1.5);
const MENU_ITEM_HEIGHT = 60;

export {
  DEFAULT_BORDER_WIDTH,
  DEFAULT_LIST_ITEM_FONT_SIZE,
  DEFAULT_LIST_ITEM_HEIGHT,
  COLLAPSIBLE_MENU_HEIGHT,
  COLLAPSIBLE_ICON_SIZE,
  MENU_ITEM_HEIGHT,
};
